spring.application.name=microservicio
server.port=8080

# === Almacenamiento temporal en EFS (Criterio 1) ===
# Carpeta donde esta montado el EFS dentro del contenedor.
efs.ruta-temporal=${EFS_PATH:/mnt/efs/guias}

# === AWS S3 (Criterios 2, 3, 4, 5) ===
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${S3_BUCKET:guiabucket-s3-2026}
